### PR TITLE
reports: 20190928 Bali Blockchain Confex 2019 in Legian, Indonesia (Update)

### PR DESCRIPTION
**Pull request by duyenemdo**
_Edit by xaur: removing the full copy of the report from this comment to prevent duplication and ease scrolling. All content is preserved in the source branch and will be merged in master._

### CODE REVIEW

**Comment by xaur** [comment]
Hey, do you plan more changes?

**Comment by raedah** [comment]
that should be it

**Comment by xaur** [comment]
Removed full copy of the report from the description of this PR (first comment). There's no need to copy it here because it is already saved in the Git commit and branch.

**Comment by xaur** [comment]
I reworded a few sentences to improve readability. You can see all my changes here: https://github.com/decredcommunity/events/pull/12/commits/e60e1bc0

One thing I wasn't certain about is this:

> Since there are so many coins and tokens are launched, if we do not keep getting Decred to people who  already knew it.

The `since ..., if ...` looks incomplete without the final `, then ...`. I changed to:

> Since so many coins and tokens have launched, we need to keep bringing Decred to people who already know it.

If you meant something else please let me know. All rest is good. Thanks.

**Comment by duyenemdo** [comment]
You got the point! Thank you so much! All good 👍

**Comment by xaur** [comment]
Awesome, thanks. Merged in master.

**Pull request closed without merging**
