### PR TITLE
reports: 20190925 La Conexión and Argentina Crypto Fest

### PR DESCRIPTION
**Pull request by 3lian**
La Conexion Buenos Aires report.

### CODE REVIEW

**Comment by xaur** [comment]
Hey, got some questions before I process it further

> Participants: La Conexión ~100 
> attracted around 150 people

Which number to use?

> where La Conexión is celebrated

Doesn't look like a holiday, can I use "takes place"?

> Pablo and Nacho

Got their chat or Twitter handles?

Did meeting with Pablo and Nacho, and the visit to Espacio Bitcoin, happen on the same day as the Crypto Fest? If not, which dates?

Finally, what do you think about splitting this doc into two separate reports for La Conexion and Crypto Fest? Or are they closely related?

**Comment by 3lian** [comment]
About assistance, there were 150 between the two days 

"takes place" sounds much better 

they're @pablito and @nachito on Riot

First meeting with pablito and nachito was on Wednesday 2nd and Espacio Bitcoin on Thursday 3th

I agree that there is enough information for two reports, not sure where to put the two paragraphs on the extra meetings tho

let me take a look at the text to change it

**Comment by xaur** [comment]
> I agree that there is enough information for two reports, not sure where to put the two paragraphs on the extra meetings tho

I'm not sure either, just wanted to throw this idea at you :) We can keep all in one report, split in two or even split the two "community visits" into a 3rd report. There was a similar situation in a Vietnam report where two events next to each other were visited in one trip.

By the way in what cities did you meet with DCR Comic and Espacio Bitcoin?

**Comment by 3lian** [comment]
DCRComic team meeting was in Buenos Aires 
Espacio Bitcoin is also in Buenos Aires

**Comment by xaur** [comment]
Ok thanks for all clarifications. Does it look good to merge?

**Comment by 3lian** [comment]
Looks good to go!!

**Comment by xaur** [comment]
Merged. Thanks for the great work! Final link:

https://github.com/decredcommunity/events/blob/master/reports/20190925-la-conexion-buenos-aires-argentina.md

**Pull request closed without merging**
