### PR TITLE
reports: 20190524 Blockchain, AI & Digital Assets Conference 2019 in Lagos, Nigeria

### PR DESCRIPTION
**Pull request by metaclips**
Location: Ozumba Mbadiwe Road, Victoria Island, Lagos, Nigeria.
Date: 24-05-2019

### CODE REVIEW

**Comment by xaur** [comment]
@metaclips thanks for the reports!

I fixed formatting and did minortext adjustments. Please check the commits if everything looks right.

Questions:

* are names of Decred attendees from matrix, slack or twitter?
* what is "flash coin", what is the proper title?
* are these from Lagos too?
  * https://twitter.com/BlockchainNG/status/1134763791432986625
  * https://twitter.com/BlockchainNG/status/1134765395469058048
  * https://twitter.com/BlockchainNG/status/1134767002667667456

**Comment by metaclips** [comment]
* Twitter
* A cryptocurrency Flashcoin.io
* Yes

**Comment by xaur** [comment]
Thanks @metaclips I added links to Twitter accounts. Final draft is [here](https://github.com/metaclips/events/blob/master/reports/20190524-blockchain-ai-digital-assets-conference-lagos-nigeria.md), if all looks right please let me know and I'll release.

**Comment by metaclips** [comment]
Looks okay

**Comment by xaur** [comment]
Done. This is the final URL, please submit to Reddit:

https://github.com/decredcommunity/events/blob/master/reports/20190524-blockchain-ai-digital-assets-conference-lagos-nigeria.md

**Pull request closed without merging**
