### PR TITLE
reports: 20191121 Africa Fintech Summit in Addis Ababa, Ethiopia

### PR DESCRIPTION
**Pull request by xaur**

### CODE REVIEW

**Comment by xaur** [comment]
@nottrunner I fixed typos and formatting, you can check the diffs above. The only remaining issue is photos don't show up when linked this way. Can you please provide direct links to images or host them elsewhere?

**Comment by nottrunner** [comment]
Here are the images

AFTS 3
AFTS 2
AFTS breakout 1

**Comment by xaur** [comment]
Thanks for uploading. Here's the draft preview: https://github.com/decredcommunity/events/blob/addis/reports/20191121-africa-fintech-summit-addis-ababa-ethiopia.md

Please give me a final ack that everything looks right before I merge.

**Comment by nottrunner** [comment]
Looks good to go.

**Comment by xaur** [comment]
Great, merged. Final link:

https://github.com/decredcommunity/events/blob/master/reports/20191121-africa-fintech-summit-addis-ababa-ethiopia.md

**Pull request closed without merging**
