### PR TITLE
index: add 20201216.1

### PR DESCRIPTION
**Pull request by xaur**
File link: https://github.com/decredcommunity/events/blob/uamx/index/20201216.1.yml

@adcadde I added a few bits but couldn't extract much.

### CODE REVIEW

**Comment by xaur** [comment]
@adcadde thanks! This looks good to merge as is, but I wonder if we should add one little detail - were all viewers studnes of UAM-X? Did they ask anything or got interested by something specific?

**Comment by adcadde** [comment]
Yes, absolutely. I can add that note.

**Review by adcadde — CHANGES_REQUESTED** [review]
Notes: LAM_UAMX is a lab created with the purpose of spreading digital culture, attendees were students of UAM-X interested in learning about decentralized organizations.

**Comment by xaur** [comment]
Thanks, added. Final link:

https://decredcommunity.github.io/events/index/20201216.1

**Pull request closed without merging**
