### PR TITLE
reports: 20191204 Decred Demo at Blockchain Centre Talk & Trade in Melbourne, Australia

### PR DESCRIPTION
**Pull request by PrimeDominus**
We are waiting on more photos to be provided. However, I've PR'd this regardless so you're aware of the event details in case we're too late for Decred Journal etc.

### CODE REVIEW

**Comment by xaur** [comment]
Thanks for the report! Since the event was in December, it will go into December Journal so no rush.

**Comment by PrimeDominus** [comment]
This is as ready as it's gonna be, since the other photos don't meet quality standards.

**Comment by xaur** [comment]
Sorry for the lag @PrimeDominus. Please let me know if my fixes above are ok before I merge.

**Comment by PrimeDominus** [comment]
Looks all good. Thanks for the extra bits :)

**Comment by xaur** [comment]
Sorry for another delay! Merged, final link:

https://github.com/decredcommunity/events/blob/master/reports/20191204-blockchain-centre-talk-and-trade-melbourne-australia.md

**Pull request closed without merging**
