### PR TITLE
reports: 20190928 Bali Blockchain Confex 2019 in Legian, Indonesia

### PR DESCRIPTION
**Pull request by duyenemdo**
_Edit by xaur: removed photos to avoid duplication_

### CODE REVIEW

**Comment by duyenemdo** [comment]
_Edit by xaur: removed all except photos to avoid duplication, all content is in the committed file. Keeping references to photos below so that GitHub wouldn't "garbage-collect" them (I don't know how it works, just guessing)_

photo_2019-10-08 09 07 25
dcr
photo_2019-10-08 09 49 41
4e3523539a337c6d2522
58eaccc575a593fbcab4
78f16424dc443a1a6355
a0525626ef4609185057
c1f797c32ea3c8fd91b2
f4ebe6a35fc3b99de0d2

**Comment by xaur** [comment]
@duyenemdo Thanks for another great report and great job at the event! What a beautiful place!

Some issues below

1\. I corrected the formatting and used "Duyen Em" for a full name like in previous report. I also reworded a few sentences. Please let me know if everything is correct. You can my commits above to see individual changes.

2\. "Information gets from the conference:" supposed to have a list after it?

3\. "There are 2 upcoming events" but only one event listed afterwards, what is the second?

4\. "One from HiBTC" did you mean Hi**t**BTC?

5\. I assume in "Programme developer" and "group of 9 programme" you mean programmers or developers - people writing programs.

**Comment by xaur** [comment]
@duyenemdo edited two of your comments above to remove duplication and have less scrolling here. All content is in the committed file so nothing is lost.

**Comment by duyenemdo** [comment]
Thank you so much for your help!

About your questions:

1. Thank you for using my full name.  And, Yes, everything is corrected.

2 + 3. People mentioned 2 conferences but giving only one name. The other's
name was forgotten.

4. No, it is  HiBTC, It  is not HitBTC. "H-i-B-T-C". It is a new shared
digital asset trading platform.

5. Yes, you are right.

Thank you again for your effort.

Vào Th 3, 8 thg 10, 2019 vào lúc 18:07 xaur <notifications@github.com> đã
viết:

**Comment by xaur** [comment]
Ok thanks for clarifications. I made final fixes and merged, here's the final link you can post around:

https://github.com/decredcommunity/events/blob/master/reports/20190928-bali-block-confex-legian-indonesia.md

Cheers

**Comment by duyenemdo** [comment]
Thank you!

Vào Th 4, 9 thg 10, 2019 vào lúc 01:01 xaur <notifications@github.com> đã
viết:

**Pull request closed without merging**
