### PR TITLE
Decred fifth anniversary event at Casablanca Morocco

### PR DESCRIPTION
**Pull request by Insaf01**

### CODE REVIEW

**Comment by xaur** [comment]
@Insaf01 thanks for the event! I updated your master branch and placed the new file on top of the latest, and then made a few fixes to the format and wording. On what platform(s) was the event livestreamed?

**Comment by Insaf01** [comment]
Thanks bee, this is the link for the live: https://www.facebook.com/OMJDC/videos/128889319097577/, the quality was not so good

**Comment by xaur** [comment]
Ok published, thanks for the event @Insaf01!

https://decredcommunity.github.io/events/index/20210206.1

FYI if you get ideas how to improve the above page feel free to post in #85.

And if you need a reference how individual fields work, see [format spec](https://github.com/decredcommunity/events/blob/master/docs/index-spec.md).

**Comment by xaur** [comment]
@Insaf01 forgot to add - try using non-master "feature branches" for future PRs (a new branch for each PR). This way you won't have any issues with master jumping back and forth, which might cause trouble when updating.

**Pull request closed without merging**
