### PR TITLE
index: 20220206.1 Decred 6th Anniversary

### PR DESCRIPTION
**Pull request by xaur**
[Rendered](https://github.com/decredcommunity/events/blob/cake6/index/20220206.1.yml).

### CODE REVIEW

**Comment by xaur** [comment]
@Insaf01 a cake deserves an index entry! Please review what I've filled so far and feel free to click Edit and add anything missing.

**Comment by xaur** [comment]
Thanks for the update @Insaf01 . I need one last little detail.

I took the start UTC time `2022-02-06 15:00` from [this tweet](https://twitter.com/in_insaf/status/1488816861093453825) that said `4:00 p.m.` in Casablanca time UTC+1. Can you please confirm the timezone of the end time `18:00`, is it UTC or +1?

**Comment by Insaf01** [comment]
Thank you @xaur 
For the time zone here I used UTC time, sorry for the confusion

**Comment by xaur** [comment]
Thanks, published now:

https://decredcommunity.github.io/events/index/20220206.1

**Pull request closed without merging**
