### PR TITLE
reports: 20190701 Wharton Cryptogovernance Workshop in San Francisco, USA

### PR DESCRIPTION
**Pull request by xaur**

### CODE REVIEW

**Comment by xaur** [comment]
@nottrunner thanks for the report!

Questions/issues:

* What "SegWit process" took place in Ethereum?
* How to read "Governance of vs by Blockchain"? I can't parse "of vs by"
* Images hosted this way cannot be embedded on GitHub. If there is a way to generate an embeddable link please do. If not, we can drop the embeds and just leave the links.

**Comment by xaur** [comment]
@nottrunner I transplanted your gist's history as a branch (all changes saved) and fixed formatting. You can see changes and check the diffs here: https://github.com/decredcommunity/events/commits/wharton07

and preview here: https://github.com/decredcommunity/events/blob/wharton07/reports/20190701-wharton-governance-workshop-san-francisco-usa.md

**Comment by nottrunner** [comment]
- Sorry the Segwit process was related to Bitcoin not Ethereum
- Governance of Blockchain Networks versus Governance leveraging Blockchain solutions
- No sure how to create embed links can you just download the images and embed them?

**Comment by xaur** [comment]
@nottrunner should I replace all "Ethereum"-s with "Bitcoin"-s in the following paragraphs?

> Decred occupied a good portion of airtime during the conversation about governance in practice. The conversation started with a well detailed summary of how the SegWit process went down in the Ethereum community. This provided the opportunity to contrast Ethereum and Decred which I and a number of other participants gladly jumped on.

> Phrases like: "If Ethereum has a clear and transparent governance process like Decred...." were used to highlight the value of an explicit and transparent process (Decred) vs an opaque process (Ethereum).

**Comment by nottrunner** [comment]
Here are the images.  Are these embeddable? 

IMG_20190702_081228_7
Crypto Governance Roundtable
IMG_20190701_164754_7
IMG_20190701_082032_6

**Comment by xaur** [comment]
@nottrunner, yes these work and I [embedded](https://github.com/decredcommunity/events/blob/wharton07/reports/20190701-wharton-governance-workshop-san-francisco-usa.md) them. Thanks for uploading. Great view!

Just the segwit issue remains, please check my previous comment.

**Comment by nottrunner** [comment]
Yes

**Comment by xaur** [comment]
Ok [here](https://github.com/decredcommunity/events/pull/6/commits/1eb94eadd809683d9cb8ba59d41b02d2dda5ca4f) is the final edit @nottrunner

I merged the report to the master branch, final URL:

https://github.com/decredcommunity/events/blob/master/reports/20190701-wharton-governance-workshop-san-francisco-usa.md

If all looks right please share on Reddit, very good read.

**Review by nottrunner — APPROVED** [review]

**Pull request closed without merging**
