### PR TITLE
index: 20200917 Hablemos Decred 13

### PR DESCRIPTION
**Pull request by 3lian**

### CODE REVIEW

**Comment by xaur** [comment]
@3lian thanks. Please review if all my fixes above are ok.

**Comment by xaur** [comment]
@3lian was this also streamed/uploaded to Facebook? Is there a link?

**Comment by 3lian** [comment]
yes, this is the stream on facebook https://www.facebook.com/watch/live/?v=1585505394960700&ref=search 

we try to concentrate the audience on youtube but it gets broadcasted on youtube, facebook and twitter

**Comment by xaur** [comment]
Thanks. I added the link and merged.

Temporary link (will move to master ultimately):

https://github.com/decredcommunity/events/blob/index/index/1601073588.yml

**Comment by xaur** [comment]
Now in master: https://github.com/decredcommunity/events/blob/master/index/20200917.1.yml

**Pull request closed without merging**
