### PR TITLE
Oct-Nov 2020 Latam events batch

### PR DESCRIPTION
**Pull request by xaur**
@3lian I've created index entries for events I found via Latam 4-5 reports, items you submitted to DJ a month ago and what I found via Decred_ES Twitter.

Please review if each field in each file is correct and check the questions below each item. I marked places I could not fill with `?` and `{ blabla }`.

It is quite a bit of work to review and fill but I did my best to pre-fill with everything I could find. _(so many Latam events to process is a nice problem to have!)_

Click Pencil icon to edit files directly without the pull request back and forth. Let me know if you would like to delegate this and I will grant direct access to more people.

**Update Dec-11**: In order to help with finishing this I'm splitting this in two groups. All items ordered from oldest to newest.

**Group 1**: I think these look good enough and only need a quick "ok" to move to master:

- [x] [Let's Talk Decred 15: DeFi, NFTs and the future of investments](https://github.com/decredcommunity/events/blob/oct/index/20201002.1.yml)

- [x] [Decentralized Governance Panel with Crypto Resources Academy](https://github.com/decredcommunity/events/blob/oct/index/20201002.2.yml)

- [x] [Criptolugares Instagram live on Politeia: How to access funding for Decred projects](https://github.com/decredcommunity/events/blob/oct/index/20201008.1.yml)

- [x] [Let's Talk Decred 16: Cryptocurrencies in Venezuela](https://github.com/decredcommunity/events/blob/oct/index/20201009.1.yml)

- [x] [Let's Talk Decred 17: 21 Heads Crypto Art Show](https://github.com/decredcommunity/events/blob/oct/index/20201016.1.yml)

- [x] [Let's Talk Decred 18: What is Decred?](https://github.com/decredcommunity/events/blob/oct/index/20201023.1.yml)

- [x] [Lastest updates on Decred v1.6 - Instagram live with CriptoLugares](https://github.com/decredcommunity/events/blob/oct/index/20201029.2.yml)

- [x] [Let's Talk Decred 19: Bitcoin in real life](https://github.com/decredcommunity/events/blob/oct/index/20201030.1.yml)

- [x] [Let's Talk Decred 20: Cryptocurrencies, blockchain and journalism](https://github.com/decredcommunity/events/blob/oct/index/20201105.1.yml)

**Group 2**: These miss some details:

Hint: Ctrl-F and search for `?` to quickly find missing info to fill.

- [x] [Introduction to blockchain API for Decred (dcrdata)](https://github.com/decredcommunity/events/blob/oct/index/20201017.1.yml)

- [x] [CCOSS 2020](https://github.com/decredcommunity/events/blob/oct/index/20201019.1.yml)

- [x] [Blockchain and Cryptocurrencies](https://github.com/decredcommunity/events/blob/oct/index/20201029.1.yml)

- [x] [Blockchain Summit Latam Online 2020](https://github.com/decredcommunity/events/blob/oct/index/20201102.1.yml)

- [x] [Talent Land Latinoamerica](https://github.com/decredcommunity/events/blob/oct/index/20201109.1.yml)

- [x] [Hablemos Decred 21](https://github.com/decredcommunity/events/blob/oct/index/20201112.1.yml)

### CODE REVIEW

**Comment by 3lian** [comment]
Dropping comments here and also in github files:

#### Let's Talk Decred 17: 21 Heads Crypto Art Show

> was this organized by Decred Latam? meetup.com announcement doesn't mention Decred 

no, this was organised by bitcoin embassy and Decred_ES joined after the meet was launch

> why does this tweet say Oct 19? Is it a mistake?

I think is a mistake

#### CCOSS 2020

> did it happen?

yes 

> how did it go?

CCOSS team transmitted through a dedicated page event, then uploaded the videos to YouTube. People connected that day were around 1,500 (had to rely on their verbal input)

> was the event in English?

Spanish

> are there video links?

https://youtu.be/TuRAeBmnScQ?list=PLnLzwYW6HOC6ekKb_Ptb29OnfbXGcPmJx

---

> Cripto Latin Fest Online 2020

Getting more details on this

> was this a livestream? https://twitter.com/Decred_ES/status/1318326206220128257

this was re-shared by Decred _ES

> is this an "event"? https://twitter.com/Decred_ES/status/1323737929429245955

I'll say yes but it goes through several weeks

_(edited by xaur: fix formatting)_

**Comment by xaur** [comment]
@3lian thanks for the extra info!

I might have missed what was Decred participation in 21 Heads Crypto Art Show? Was there a talk or a presentation?

**Comment by xaur** [comment]
> > was this a livestream? https://twitter.com/Decred_ES/status/1318326206220128257
> 
> this was re-shared by Decred_ES

Do you mean it was recorded and published on their YT (not livestreamed)?

**Comment by xaur** [comment]
re "Introduction to blockchain API for Decred (dcrdata)"

- was it livestreamed or recorded in advance?
- was there interaction with participants? If yes, was it done via YouTube comments?

**Comment by xaur** [comment]
Created 2 new entries for review:

- [Blockchain Learning Challenge - Decred](https://github.com/decredcommunity/events/blob/oct/index/20201026.1.yml)

- [Talent Land Latinoamerica](https://github.com/decredcommunity/events/blob/oct/index/20201109.1.yml)

Also pushed some small fixes to existing ones.

**Comment by xaur** [comment]
@3lian when one of the files in this PR looks good to you please indicate that with a comment like "Hablemos Decred 15: lgtm". This way I will know it is approved and will proceed to move it to the master branch.

**Comment by xaur** [comment]
Added [Hablemos Decred 21](https://github.com/decredcommunity/events/blob/oct/index/20201112.1.yml).

**Comment by 3lian** [comment]
> @3lian thanks for the extra info!
> 
> I might have missed what was Decred participation in 21 Heads Crypto Art Show? Was there a talk or a presentation?

No presentation on our part, just a quick thanks and "follow us" after the panel

**Comment by 3lian** [comment]
> @3lian when one of the files in this PR looks good to you please indicate that with a comment like "Hablemos Decred 15: lgtm". This way I will know it is approved and will proceed to move it to the master branch.

ok

**Comment by xaur** [comment]
> No presentation on our part, just a quick thanks and "follow us" after the panel

Hmm then I dont follow what was Decred's role in that event. Was it an organizer or a sponsor?

**Comment by xaur** [comment]
Moved to separate PRs to make this one a bit lighter:

- Blockchain Learning Challenge - Decred -> #78

- Cripto Latin Fest Online 2020 -> #79

**Comment by 3lian** [comment]
Group 1 events are ready and added changes to Group 2, thanks!

**Comment by xaur** [comment]
Added all entries to master. They will show on the site with the next rebuild.

Thank you so much for your patience with this and for the awesome outreach work!

**Pull request closed without merging**
